### PR TITLE
🆕 Curse Binding and Vanishing

### PR DESCRIPTION
**Pull request by curio-sitas**
Add curse enchantments to the player : 
- Curse of Binding to the armor
- Curse of Vanishing to all other items in the inventory

### CODE REVIEW

**Comment by curio-sitas** [comment]
> as it is very punishing speci

Hello ! I agree, this event is quite sadic. Maybe we can choose only a few random items or just apply curse of binding to the armor and no curse of vanishing ?

Also, if you are interested, i can make a French translation file for the mod.

**Comment by juancarloscp52** [comment]
We already have a [event](https://github.com/juancarloscp52/Entropy/blob/1.19/src/main/java/me/juancarloscp52/entropy/events/db/CurseRandomGearEvent.java) that curses random items in the inventory / armor. I think your event should be ok with only cursing the armor.

> Also, if you are interested, i can make a French translation file for the mod.

Yeah of course! if you have the time, any contribution is greatly appreciated ;)

Thanks!

**Comment by juancarloscp52** [comment]
Seems good, but cannot merge it as it is targeting `juancarloscp52:1.19`, could you re-open the PR targeting` juancarloscp52:1.19.3`? Thanks!

**Comment by curio-sitas** [comment]
> Seems good, but cannot merge it as it is targeting `juancarloscp52:1.19`, could you re-open the PR targeting` juancarloscp52:1.19.3`? Thanks!

I'll do that later in the day !

**Pull request merged**
