### PR TITLE
Youtube Integration

### PR DESCRIPTION
**Pull request by Kanawanagasaki**
Adds youtube integration, allows to connect youtube account and parse live broadcasts's chat messages to vote for event.
Requires to create new API project in [Google Cloud Console](https://console.cloud.google.com)

1. Create api project in [Google Cloud Console](https://console.cloud.google.com)
2. Go to [API & Services](https://console.cloud.google.com/apis/dashboard)
3. Configure [OAuth consent screen](https://console.cloud.google.com/apis/credentials/consent)
- With `https://www.googleapis.com/auth/youtube` scope
- With test users that will use youtube integration
- App domains and Authorized domains don't matter
4. In [Library](https://console.cloud.google.com/apis/library) enable [YouTube Data API v3](https://console.cloud.google.com/apis/library/youtube.googleapis.com)
5. In [Credentials](https://console.cloud.google.com/apis/credentials) create OAuth Client ID
6. In Minecraft in Entropy options insert Client Id and Secret from OAuth Client ID credential
7. Click on Authorize button and authorize modification to interact with Youtube account

### CODE REVIEW

**Comment by juancarloscp52** [comment]
Thank you so much for this contribution! Had to change the URL handling for opening a link in the browser to the built in minecraft one, as it was not working on linux (at least not in my distro).

Awesome work!

**Comment by Kanawanagasaki** [comment]
Yeah, i didn't know how to open browser in java at all and also i on windows so i end up googling how to do so. But apparently there is a util method to do so.
Also i think we need to add step-by-step instruction on how to add yt integration because inexperienced people will be lost in google cloud console.

**Comment by juancarloscp52** [comment]
yep, I'll record a video guide similar to the discord one when the update releases

**Comment by juancarloscp52** [comment]
Hello again! I've been testing it a bit more while recording the guide, and I've noticed that during the authorization process, GCP does not send a refresh token if the user had previously authorized and then revoked the application. This makes it impossible to authorize if the user has previously used the integration in, for example, another minecraft instance. The code handling this is at `YoutubeApi.java line 95` 

I've been testing some things, and different token request parameters with no luck. I think I have GCP console configured correctly as it was working yesterday.

Do you have any idea or possible solution?  Thanks

**Comment by Kanawanagasaki** [comment]
I cannot reproduce.

My steps was:
1. Click `Authorize` on Integrations screen with `Youtube` selected
2. Authorize with browser
*got a refresh token*
3. Revoke application https://myaccount.google.com/u/1/permissions
4. Click `Authorize` on Integrations screen with `Youtube` selected
5. Authorize with browser
*got a refresh token*
6. Revoke application https://myaccount.google.com/u/1/permissions
7. Close minecraft and open it back
8. Click `Authorize` on Integrations screen with `Youtube` selected
9. Authorize with browser
*got a refresh token*

**Comment by juancarloscp52** [comment]
Hmm must be something on my end then, I'll test a bit more... thanks

**Comment by Kanawanagasaki** [comment]
Ohh, after watching your youtube video tutorial i see now why you don't have a refresh token. When you create OAuth Client ID as application type you specify Web Application, i made Youtube integration to use Desktop App authentication.

Sorry, my fault that i didn't specify what type of application it should be.

**Comment by Kanawanagasaki** [comment]
It still will use browser to authorize but it not require strict redirect url. So on step 5 you don't need to add authorized URI

**Comment by juancarloscp52** [comment]
oh I understand, no problem!. Since it seems to be working fine following the YT video and after the changes in 052fd8f41a156d8ce7097fdfc6f6464b148f7c02, I'll keep the process as it is. Thanks!

**Comment by Kanawanagasaki** [comment]
I dislike the fixed port.
Also if you go web app authorization route then you don't need:
- https://github.com/juancarloscp52/Entropy/blob/1.19/src/main/java/me/juancarloscp52/entropy/client/integrations/youtube/YoutubeApi.java#L54-L56 
- https://github.com/juancarloscp52/Entropy/blob/1.19/src/main/java/me/juancarloscp52/entropy/client/integrations/youtube/YoutubeApi.java#L79

**Comment by juancarloscp52** [comment]
ok I understand, later today I'll try the Desktop App configuration and if it all works I'll undo 052fd8f41a156d8ce7097fdfc6f6464b148f7c02 and update the video. So it is as it was originally

**Pull request merged**
